services:
  nestjs_starter_postgres: # Needs updating
    image: postgres:alpine
    container_name: nestjs_starter_postgres # Needs updating
    ports:
      - '5434:5432'
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nestjs_starter_postgres_data:/var/lib/postgresql/data # Needs updating

  nestjs_starter_redis: # Needs updating
    image: redis:alpine
    container_name: nestjs_starter_redis # Needs updating
    ports:
      - '6380:6379'
    volumes:
      - nestjs_starter_redis_data:/data # Needs updating

networks:
  default:
    name: nestjs_starter # Needs updating

volumes:
  nestjs_starter_postgres_data: # Needs updating
  nestjs_starter_redis_data: # Needs updating
